version: '3'

services:
  web:
    build: .
    ports:
      - "9090:8000"
    command: ["bash","-c","php artisan migrate && php artisan db:seed && php artisan serve --host 0.0.0.0"]
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: task
      DB_USERNAME: task
      DB_PASSWORD: task

  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task
      MYSQL_USER: task
      MYSQL_PASSWORD: task
    ports:
        - "33061:3306"